//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TangramService.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CmsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CmsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TangramCMS.App_LocalResources.CmsResource", typeof(CmsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACL record deleted..
        /// </summary>
        internal static string AclDeleted {
            get {
                return ResourceManager.GetString("AclDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACL record already exist..
        /// </summary>
        internal static string AclExist {
            get {
                return ResourceManager.GetString("AclExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACL record not exist..
        /// </summary>
        internal static string AclNotExist {
            get {
                return ResourceManager.GetString("AclNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACL record saved..
        /// </summary>
        internal static string AclSaved {
            get {
                return ResourceManager.GetString("AclSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous({0}).
        /// </summary>
        internal static string AnonymousName {
            get {
                return ResourceManager.GetString("AnonymousName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection {0} already exist..
        /// </summary>
        internal static string CollectionAlreadyExist {
            get {
                return ResourceManager.GetString("CollectionAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection {0} created..
        /// </summary>
        internal static string CollectionCreated {
            get {
                return ResourceManager.GetString("CollectionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection {0} deleted..
        /// </summary>
        internal static string CollectionDeleted {
            get {
                return ResourceManager.GetString("CollectionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection {0} not exist..
        /// </summary>
        internal static string CollectionNotExist {
            get {
                return ResourceManager.GetString("CollectionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document already exist..
        /// </summary>
        internal static string DocumentAlreadyExist {
            get {
                return ResourceManager.GetString("DocumentAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document deleted..
        /// </summary>
        internal static string DocumentDeleted {
            get {
                return ResourceManager.GetString("DocumentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is missing Id..
        /// </summary>
        internal static string DocumentMissingId {
            get {
                return ResourceManager.GetString("DocumentMissingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document (Id: {0}) not exist..
        /// </summary>
        internal static string DocumentNotExist {
            get {
                return ResourceManager.GetString("DocumentNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document saved..
        /// </summary>
        internal static string DocumentSaved {
            get {
                return ResourceManager.GetString("DocumentSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type {0} already exist..
        /// </summary>
        internal static string DocumentTypeAlreadyExist {
            get {
                return ResourceManager.GetString("DocumentTypeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type {0} deleted..
        /// </summary>
        internal static string DocumentTypeDeleted {
            get {
                return ResourceManager.GetString("DocumentTypeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type is missing Id..
        /// </summary>
        internal static string DocumentTypeMissingId {
            get {
                return ResourceManager.GetString("DocumentTypeMissingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type is missing type name..
        /// </summary>
        internal static string DocumentTypeMissingTypeName {
            get {
                return ResourceManager.GetString("DocumentTypeMissingTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type {0} not exist..
        /// </summary>
        internal static string DocumentTypeNotExist {
            get {
                return ResourceManager.GetString("DocumentTypeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type {0} saved..
        /// </summary>
        internal static string DocumentTypeSaved {
            get {
                return ResourceManager.GetString("DocumentTypeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize scucceeded..
        /// </summary>
        internal static string InitializeSucceeded {
            get {
                return ResourceManager.GetString("InitializeSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Administrators could only applied when no users are Administrators..
        /// </summary>
        internal static string InvalidAdministratorsRecovery {
            get {
                return ResourceManager.GetString("InvalidAdministratorsRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize could only applied to database without users and roles..
        /// </summary>
        internal static string InvalidInitialization {
            get {
                return ResourceManager.GetString("InvalidInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization has been denied for this request..
        /// </summary>
        internal static string NoAuthorization {
            get {
                return ResourceManager.GetString("NoAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent not exist..
        /// </summary>
        internal static string ParentNotExist {
            get {
                return ResourceManager.GetString("ParentNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Administrators succeeded..
        /// </summary>
        internal static string RecoverAdministratorsSucceeded {
            get {
                return ResourceManager.GetString("RecoverAdministratorsSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} add role {1} succeeded..
        /// </summary>
        internal static string RoleAdded {
            get {
                return ResourceManager.GetString("RoleAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {0} already added to user {1}..
        /// </summary>
        internal static string RoleAlreadyAdded {
            get {
                return ResourceManager.GetString("RoleAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {0} already exist..
        /// </summary>
        internal static string RoleAlreadyExist {
            get {
                return ResourceManager.GetString("RoleAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {0} created..
        /// </summary>
        internal static string RoleCreated {
            get {
                return ResourceManager.GetString("RoleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {0} deleted..
        /// </summary>
        internal static string RoleDeleted {
            get {
                return ResourceManager.GetString("RoleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role {0} not exist..
        /// </summary>
        internal static string RoleNotExist {
            get {
                return ResourceManager.GetString("RoleNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection already exist..
        /// </summary>
        internal static string SelectionAlreadyExist {
            get {
                return ResourceManager.GetString("SelectionAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection {0} deleted..
        /// </summary>
        internal static string SelectionDeleted {
            get {
                return ResourceManager.GetString("SelectionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection is missing Id..
        /// </summary>
        internal static string SelectionMissingId {
            get {
                return ResourceManager.GetString("SelectionMissingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection is missing SelectionId..
        /// </summary>
        internal static string SelectionMissingSelectionId {
            get {
                return ResourceManager.GetString("SelectionMissingSelectionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection not exist..
        /// </summary>
        internal static string SelectionNotExist {
            get {
                return ResourceManager.GetString("SelectionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection saved..
        /// </summary>
        internal static string SelectionSaved {
            get {
                return ResourceManager.GetString("SelectionSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} created..
        /// </summary>
        internal static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} not exist..
        /// </summary>
        internal static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} restored..
        /// </summary>
        internal static string UserRestored {
            get {
                return ResourceManager.GetString("UserRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} suspended..
        /// </summary>
        internal static string UserSuspended {
            get {
                return ResourceManager.GetString("UserSuspended", resourceCulture);
            }
        }
    }
}
